kernel:
  image: linuxkit/kernel:4.9.54
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:98e95fb67e8afcf02c09ba927e4b357fec42977a
  - linuxkit/runc:991ef358ad8fc1111d64f4d8071f2009cc561f6a
  - linuxkit/containerd:eaf0d615cfceb9d854408dd3c80429ee8ac4d051
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:aa685261ceb2557990dcfe9dd8824c6b9ec416e2
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: conf-linuxkit/getty:6c8de371697406204c81c6f1f48fe30d1db211dd-amd64
    env:
     - INSECURE=true
  - name: tomcat
    image: conf-linuxkit/lkt-tomcat:7d6f422e1c73cbea549bb77b7884ef31b2432a1c-amd64
    net: host
trust:
  org:
    - linuxkit
