kernel:
  image: linuxkit/kernel:4.9.47
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:6d11a1f9d299d3425e78cce80dfba8b236d20412
  - linuxkit/runc:a1b564248a0d0b118c11e61db9f84ecf41dd2d2a
  - linuxkit/containerd:7d97282aebe36040fcdd3378a95562d440d34a9d
services:
  - name: getty
    image: devfest-hello-tetris:latest
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
