kernel:
  image: linuxkit/kernel:4.9.54
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:98e95fb67e8afcf02c09ba927e4b357fec42977a
  - linuxkit/runc:991ef358ad8fc1111d64f4d8071f2009cc561f6a
  - linuxkit/containerd:eaf0d615cfceb9d854408dd3c80429ee8ac4d051
services:
  - name: getty
    image: devfest-linuxkit/devfest-hello-world:e3ccd2c68c882c448fdb5aaf211dfeba1b37eac5-dirty-amd64
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
