kernel:
  image: linuxkit/kernel:4.9.40
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:4dcee04c04c900a5796dc719f8d16fea7e771059
  - linuxkit/runc:f5960b83a8766ae083efc744fa63dbf877450e4f
  - linuxkit/containerd:8fc87b7f465bde9ece781899a007f47b6d3c096b
  - pyaillet/hello-world-go:latest
services:
  - name: getty
    image: linuxkit/getty:58620cff1b0bf8b5d144d087602115e996f18a02
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit