kernel:
  image: linuxkit/kernel:4.9.53
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:7804129bd06218b72c298139a25698a748d253c6
  - linuxkit/runc:a1b564248a0d0b118c11e61db9f84ecf41dd2d2a
  - linuxkit/containerd:417f83f7b8dc1fa36acf90effe44f99c7397480a
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:d4408777ed6b6e6e562a5d4938fd09804324b33e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:a19851531487b7bfbe45dcf77e3309c127cc78a6
    env:
     - INSECURE=true
  - name: hello-server
    image: devfest-linuxkit/devfest-hello-go:da8b46a091590e84039541c09e48e2b6767b7bd6-amd64
    net: host
trust:
  org:
    - linuxkit
